# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-02 06:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('key', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('user_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('rating', models.FloatField(default=0)),
                ('about', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_key', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=255)),
                ('seen_by', models.IntegerField(default=0)),
                ('posted_on', models.DateTimeField(default=datetime.datetime(2017, 12, 2, 6, 38, 32, 74548, tzinfo=utc))),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('about', models.CharField(max_length=1000)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tg_app.Customer')),
                ('city_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tg_app.City')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.CharField(max_length=255)),
                ('longitude', models.CharField(max_length=255)),
                ('address_line', models.CharField(max_length=1000)),
                ('postal_code', models.IntegerField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tg_app.City')),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_url', models.CharField(max_length=255, unique=True)),
                ('media_type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tg_app.City')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tg_app.Customer')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tg_app.Location'),
        ),
        migrations.AddField(
            model_name='event',
            name='main_photo_url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tg_app.Media'),
        ),
        migrations.AddField(
            model_name='city',
            name='main_photo_url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tg_app.Media'),
        ),
    ]
